[package]
name = "dependency-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
pubgrub = "0.3.0"
semver = { version = "1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
